### ISSUE TITLE
Loggly EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by PorterHoskins** [melke/SlimLogger#1]
I am getting a EXC_BAD_ACCESS on line _SlimLogglyDestination.swift_ line 113. I tried moving all the references to `self.buffer` to the same queue but it doesn't seem to help. Any ideas?

**Comment by melke** [comment]
Hi @PorterHoskins, Thank you very much for reporting this. Do you have more info about when this is happening? Does it happen everytime? Does it happen at the very first log call? Are you logging something specific when this is happening?

**Comment by PorterHoskins** [comment]
I feel like it happens when I add a bunch of logs to send off all at once. It is a bit random and haven't been able to fix it yet.

**Comment by melke** [comment]
Ah, then it probably happens when the buffer is sent and reloaded when SlimLogglyConfig.maxEntriesInBuffer has been reached. Unfortunately, I'm just about to leave for a vacation. Can you try raising the value of SlimLogglyConfig.maxEntriesInBuffer to something really large and see if the problem goes away? If so, we need to find a better way of switching the buffer (I thought the serial queue would make the switch safe).

**Comment by PorterHoskins** [comment]
Ok looks like the issue was a concurrency issue. `dispatch_async(dispatch_get_global_queue(Int(QOS_CLASS_BACKGROUND.value), 0))` is a concurrent queue. Changing it to a custom made serial queue fixed it.

**Comment by melke** [comment]
Great! Would you mind sharing the solution? Maybe create a pull request?
