### ISSUE TITLE
warning on sendAsynchronousRequest

### ISSUE THREAD

**Issue by matthewchung74** [melke/SlimLogger#5]
I'm still getting a warning from using sendAsynchronousRequest. I'd be glad to take a look, unless you have something in the works already.

**Comment by melke** [comment]
Thanks for the feedback @foobar8675 
Can you describe the problem a little more? I don't get any warning in the Example project. 
Maybe you mean the SSL handshake error, due to the fact that the Loggly servers use a cipher that iOS does not accept by default? (See comment in the top section of README-LogglyDestination.md)

**Comment by matthewchung74** [comment]
Ah, I just realized it's because I have my deployment target set to 9.0. If you change the example project deployment target to 9.0, you'll see the same warning.

**Comment by SimplGy** [comment]
I got this too. Want a PR for this?

**Comment by melke** [comment]
@SimplGy Yes, that would be great!

**Comment by SimplGy** [comment]
Similar deal for `__LINE__` macros:

![image](https://cloud.githubusercontent.com/assets/548809/14826403/eb14098c-0b9a-11e6-8dfb-f1e819281ea5.png)

UPDATE: you already got that fixed in https://github.com/melke/SlimLogger/commit/631053607f806c0e89201f09b6638bfec180f9a7, awesome.
